config/routes.rb
Rails.application.routes.draw do
  root :to => 'conventions#index' #me equivoque bien cagado en el nombre

  resources :conventions 

end

app/models/convention.rb
class Convention < ActiveRecord::Base
	validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/conventions_controller.rb
class ConventionsController < ApplicationController

	def index
	end

	def new
		@convention = Convention.new
	end

	def create
		@convention = Convention.new(convention_params)
		if @convention.save
			flash[:notice] = "The congress has been created."
			redirect_to @convention
		else
			flash[:error]="The Congress could not be created"
			render :action => "new"
		end
	end

	def show
		@convention = Convention.find(params[:id])
	end
	private
		def convention_params
				params.require(:convention).permit(:name,:description, :initDate, :endDate, :place)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conventions_helper.rb
module ConventionsHelper
end

app/views/conventions/_form.html.erb
<%= form_for(@convention) do |f| %>
	<% if @convention.error.any? %>
		<h2><%= pluralize(@convention.errors.count, "error") %> prohibited this from saving</h2>

		<ul>
			<% @convention.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>	
	<% end %>

	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %><br>
	</p>	

	<p>
		<%= f.label :description %><br>
		<%= f.text_field :description %><br>
	</p>	

	<p>
		<%= f.label :initDate, "Begins" %><br>
		<%= f.text_field :initDate %><br>
	</p>	

	<p>
		<%= f.label :endDate, "Ends" %><br>
		<%= f.text_field :endDate %><br>
	</p>	

	<p>
		<%= f.label :place, "Place" %><br>
		<%= f.text_field :place %><br>
	</p>	
	<%= f.submit "Create Congress"%><br>


<% end %>

app/views/conventions/index.html.erb
<%= link_to 'New Congress', new_convention_path %>

app/views/conventions/new.html.erb
<%= render 'form' %>

app/views/conventions/show.html.erb
<h1><%= @convention.name %> </h1>

<p><%= @convention.description %> </p>
<p><%= @convention.initDate %> </p>
<p><%= @convention.endDate %> </p>
<p><%= @convention.place %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Congreso</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>